// ==================================================================================
// 模块: Config (静态配置)
// ==================================================================================
(function() {
    // 确保命名空间存在
    window.ST_PHONE = window.ST_PHONE || {};

    window.ST_PHONE.config = {
        // 主题色配置
        theme: {
            primary: '#007AFF',
            background: '#ffffff'
        },

        // 表情包库 (已整合你的数据)
        stickers: [
            // --- 基础互动 ---
            { label: "打招呼", url: "https://sharkpan.xyz/f/LgwT7/AC229A80203166B292155ADA057DE423_0.gif" },
            { label: "开心", url: "https://sharkpan.xyz/f/aVwtY/0CBEE9105C7A98E0E6162A79CCD09EFA_0.gif" },
            { label: "爱心", url: "https://sharkpan.xyz/f/53nhj/345FFC998474F46C1A40B1567335DA03_0.gif" },
            { label: "给你爱", url: "https://files.catbox.moe/sqa7c9.jpg" },
            { label: "好的", url: "https://files.catbox.moe/71kn5e.png" },
            { label: "晚安", url: "https://files.catbox.moe/duzx7n.png" },
            { label: "吃啥呢给我掰点", url: "https://files.catbox.moe/吃啥呢给我掰点tqm23r.jpg" },
            { label: "感到压力", url: "https://files.catbox.moe/感到压力ufz3ek.jpg" },
            { label: "让咪咪咪一会好吗", url: "https://files.catbox.moe/让咪咪咪一会好吗ig8pp7.jpg" },
            { label: "愚蠢的我", url: "https://files.catbox.moe/愚蠢的我3sw5uu.jpg" },
            { label: "跟我神经病计较什么", url: "https://files.catbox.moe/跟我神经病计较什么p2ymy9.jpg" },
            { label: "请问你很牛吗", url: "https://files.catbox.moe/请问你很牛吗h4osmk.jpg" },
            { label: "局促", url: "https://files.catbox.moe/局促gzosdm.jpg" },
            { label: "我很好", url: "https://files.catbox.moe/我很好zj6adv.jpg" },
            { label: "硬撑", url: "https://files.catbox.moe/硬撑qrp6dm.jpg" },
            { label: "牛马的命也是命", url: "https://files.catbox.moe/牛马的命也是命g98ofy.jpg" },
            { label: "你的良心出了点问题", url: "https://files.catbox.moe/你的良心出了点问题kmiyh6.jpg" },
            { label: "哈哈我疯啦", url: "https://files.catbox.moe/哈哈我疯啦7b5v1v.jpg" },
            { label: "这事有蹊跷", url: "https://files.catbox.moe/这事有蹊跷7jom1o.jpg" },
            { label: "哦！", url: "https://files.catbox.moe/哦！ov1hdu.jpg" },
            { label: "excuse me?", url: "https://files.catbox.moe/excuse me?cff4yf.jpg" },
            { label: "机缘巧合罢了", url: "https://files.catbox.moe/机缘巧合罢了zap7bj.jpg" },
            { label: "给你台阶", url: "https://files.catbox.moe/给你台阶hyushu.jpg" },
            { label: "要死了", url: "https://files.catbox.moe/要死了3pht7n.jpg" },
            { label: "我好累", url: "https://files.catbox.moe/我好累6fahlg.jpg" },
            { label: "很烦", url: "https://files.catbox.moe/很烦l2227m.jpg" },
            { label: "我恨这个世界", url: "https://files.catbox.moe/我恨这个世界bqit1t.jpg" },
            { label: "骂骂咧咧", url: "https://files.catbox.moe/骂骂咧咧72koiw.jpg" },
            { label: "阿弥陀佛", url: "https://files.catbox.moe/阿弥陀佛4sabpi.jpg" },
            { label: "死工作永无止境", url: "https://files.catbox.moe/死工作永无止境2bidi3.jpg" },
            { label: "狗眼看人低？", url: "https://files.catbox.moe/狗眼看人低？vz0zth.jpg" },
            { label: "按下骂人开关", url: "https://files.catbox.moe/按下骂人开关3nnxf7.jpg" },
            { label: "哦呦了不起", url: "https://files.catbox.moe/哦呦了不起5pyonu.jpg" },
            { label: "今天发什么疯好呢", url: "https://files.catbox.moe/今天发什么疯好呢mkm06b.jpg" },
            { label: "嘘", url: "https://files.catbox.moe/嘘6htwq1.jpg" },
            { label: "精神病一触即发", url: "https://files.catbox.moe/精神病一触即发sdod5d.jpg" },
            { label: "请你上吊", url: "https://files.catbox.moe/请你上吊qjjuai.jpg" },
            { label: "我永远也不会原谅你", url: "https://files.catbox.moe/我永远也不会原谅你vlxbvu.jpg" },
            { label: "做人没必要那么正常", url: "https://files.catbox.moe/做人没必要那么正常2lhe1h.jpg" },
            { label: "突然想到个馊主意", url: "https://files.catbox.moe/突然想到个馊主意43ba7g.jpg" },
            { label: "抛开内容不谈你讲得有道理", url: "https://files.catbox.moe/抛开内容不谈你讲得有道理1cmut7.jpg" },
            { label: "偷听", url: "https://files.catbox.moe/偷听xkapk3.jpg" },
            { label: "我该打", url: "https://files.catbox.moe/我该打f8bjf0.jpg" },
            { label: "姐姐我摔倒啦", url: "https://files.catbox.moe/姐姐我摔倒啦irq4ky.jpg" },
            { label: "请和我交往", url: "https://files.catbox.moe/请和我交往imo7d8.jpg" },
            { label: "送你幸福", url: "https://files.catbox.moe/送你幸福vidlif.jpg" },
            { label: "你最棒", url: "https://files.catbox.moe/你最棒bulyae.jpg" },
            { label: "每天都在想你", url: "https://files.catbox.moe/每天都在想你o0dia5.jpg" },
            { label: "Oi！", url: "https://files.catbox.moe/Oi！rcogx1.jpg" },
            { label: "皇上请翻牌子", url: "https://files.catbox.moe/皇上请翻牌子wkdcdf.jpg" },
            { label: "奴才告退", url: "https://files.catbox.moe/奴才告退wt8jqa.jpg" },
            { label: "舔狗登场", url: "https://files.catbox.moe/舔狗登场ohry21.jpg" },
            { label: "姐姐！", url: "https://files.catbox.moe/姐姐！f9587d.jpg" },
            { label: "太美了吧", url: "https://files.catbox.moe/太美了吧tctls0.jpg" },
            { label: "狗狗来咯", url: "https://files.catbox.moe/狗狗来咯k5rzrq.jpg" },
            { label: "狗狗走咯", url: "https://files.catbox.moe/狗狗走咯h4bqea.jpg" },
            { label: "不在乎小狗了吗", url: "https://files.catbox.moe/不在乎小狗了吗mqsa57.jpg" },
            { label: "请你公开我们的关系", url: "https://files.catbox.moe/请你公开我们的关系9rimsc.jpg" },
            { label: "听不懂想亲嘴", url: "https://files.catbox.moe/听不懂想亲嘴ic2n92.jpg" },
            { label: "小狗抱手机哭", url: "https://files.catbox.moe/小狗抱手机哭y7qphr.jpg" },
            { label: "求求你", url: "https://files.catbox.moe/求求你vtrw3o.jpg" },
            { label: "好的主人", url: "https://files.catbox.moe/好的主人8bvpz6.jpg" },
            { label: "小狗委屈", url: "https://files.catbox.moe/小狗委屈rbnrf1.jpg" },
            { label: "主人我以后只跟着你走", url: "https://files.catbox.moe/主人我以后只跟着你走9hvpjn.jpg" },
            { label: "等待", url: "https://files.catbox.moe/等待zl4tko.png" },
            { label: "love you", url: "https://files.catbox.moe/love youkxu26o.png" },
            { label: "呆坐", url: "https://files.catbox.moe/呆坐oxi30g.png" },
            { label: "着急", url: "https://files.catbox.moe/着急j2s53r.png" },
            { label: "急哭了", url: "https://files.catbox.moe/急哭了qt9uta.png" },
            { label: "吃我一拳", url: "https://files.catbox.moe/吃我一拳5txmzd.png" },
            { label: "警觉", url: "https://files.catbox.moe/警觉spgdwv.png" },
            { label: "鬼鬼祟祟", url: "https://files.catbox.moe/鬼鬼祟祟8ccguc.png" },
            { label: "吻手礼", url: "https://files.catbox.moe/吻手礼funa7u.png" },
            { label: "重罪", url: "https://files.catbox.moe/重罪ugt3wq.png" },
            { label: "真的吗？", url: "https://files.catbox.moe/真的吗？0xr1fh.png" },
            { label: "开心转圈", url: "https://files.catbox.moe/开心转圈0nbi2p.png" },
            { label: "严肃/板着脸", url: "https://files.catbox.moe/严肃/板着脸31ke9x.png" },
            { label: "跑过来", url: "https://files.catbox.moe/跑过来ois23f.png" },
            { label: "那咋了", url: "https://files.catbox.moe/那咋了dhp2gr.png" },
            { label: "想咋地", url: "https://files.catbox.moe/想咋地3ruhin.png" },
            { label: "哈？", url: "https://files.catbox.moe/哈？k0uru3.png" },
            { label: "心虚", url: "https://files.catbox.moe/心虚6uqxds.png" },
            { label: "怎么样打死我", url: "https://files.catbox.moe/怎么样打死我doag9c.png" },
            { label: "好厉害（不走心）", url: "https://files.catbox.moe/好厉害（不走心）tt548x.png" },
            { label: "坏笑", url: "https://files.catbox.moe/坏笑vpnmxr.png" },
            { label: "装酷", url: "https://files.catbox.moe/装酷p9v3sq.png" },
            { label: "红温", url: "https://files.catbox.moe/红温gmvx6d.png" },
            { label: "大惊失色", url: "https://files.catbox.moe/大惊失色w7olag.png" },
            { label: "难过", url: "https://files.catbox.moe/难过ydyx59.png" },
            { label: "自闭", url: "https://files.catbox.moe/自闭nhtazq.png" },
            { label: "那又如何", url: "https://files.catbox.moe/那又如何do83tr.png" },
            { label: "思考", url: "https://files.catbox.moe/思考32ql1h.png" },
            { label: "睡会儿/困", url: "https://files.catbox.moe/睡会儿/困6u5ch8.png" },
            { label: "精神涣散", url: "https://files.catbox.moe/精神涣散4oeevo.png" },
            { label: "打哈欠/好困", url: "https://files.catbox.moe/打哈欠/好困fuyq6d.png" },
            { label: "大脑过载", url: "https://files.catbox.moe/大脑过载kq9i8f.png" },
            { label: "我想想", url: "https://files.catbox.moe/我想想324d33.png" },
            { label: "按头", url: "https://files.catbox.moe/按头pfnrya.png" },
            { label: "捏爆地球", url: "https://files.catbox.moe/捏爆地球h1kt1u.png" },
            { label: "眼睛亮晶晶/期待", url: "https://files.catbox.moe/眼睛亮晶晶/期待i0ov5h.png" },
            { label: "不要和我说话", url: "https://files.catbox.moe/不要和我说话wnr64t.png" },
            { label: "不对劲", url: "https://files.catbox.moe/不对劲itw2h1.png" },
            { label: "讨好", url: "https://files.catbox.moe/讨好7fwfte.png" },
            { label: "盯——", url: "https://files.catbox.moe/盯——9za97q.png" },
            { label: "“草”", url: "https://files.catbox.moe/“草”9b800k.png" },
            { label: "老实", url: "https://files.catbox.moe/老实hgfgj3.png" },
            { label: "泪流成河", url: "https://files.catbox.moe/泪流成河nh9r23.png" },
            { label: "打电话哭哭", url: "https://files.catbox.moe/打电话哭哭8ejal5.png" },
            { label: "揉脸", url: "https://files.catbox.moe/揉脸9lmwuz.png" },
            { label: "满脸疑惑", url: "https://files.catbox.moe/满脸疑惑skv9p6.png" },
            { label: "哈特软软/好喜欢", url: "https://files.catbox.moe/哈特软软/好喜欢0bmbi0.png" },
            { label: "被训", url: "https://files.catbox.moe/被训sgkcwv.png" },
            { label: "哀怨/生闷气", url: "https://files.catbox.moe/哀怨/生闷气1n905b.png" },
            { label: "喜欢", url: "https://files.catbox.moe/喜欢opqz7o.png" },
            { label: "被吓一跳", url: "https://files.catbox.moe/被吓一跳26xc9h.png" },
            { label: "淋雨哭泣", url: "https://files.catbox.moe/淋雨哭泣l68nws.png" },
            { label: "睡了", url: "https://files.catbox.moe/睡了7wbc1d.png" },
            { label: "非常认可", url: "https://files.catbox.moe/非常认可3s5ipf.png" },

            // --- 卖萌/撒娇 ---
            { label: "乖巧", url: "https://files.catbox.moe/4dnzcq.png" },
            { label: "害羞", url: "https://files.catbox.moe/ssgpgy.jpg" },
            { label: "飞奔", url: "https://sharkpan.xyz/f/kDOi6/0A231BF0BFAB3C2B243F9749B64F7444_0.gif" },
            { label: "蹭蹭", url: "https://files.catbox.moe/9p0x2t.png" },
            { label: "期待", url: "https://files.catbox.moe/i0ov5h.png" },
            { label: "送花", url: "https://files.catbox.moe/s1t2kd.jpg" },
            { label: "可怜", url: "https://sharkpan.xyz/f/XgmcW/817B66DAB2414E1FC8D717570A602193_0.gif" },
            { label: "流口水", url: "https://sharkpan.xyz/f/j36f6/3010464DF8BD77B4A99AB23730F2EE57_0.gif" },
            { label: "可怜兮兮", url: "https://files.catbox.moe/h77bnu.png" },
            { label: "双眼放光", url: "https://files.catbox.moe/9tc8lj.png" },
            { label: "委屈哭唧唧", url: "https://files.catbox.moe/委屈哭唧唧d5bdm3.png" },
            { label: "来啦来啦", url: "https://files.catbox.moe/来啦来啦afuns1.png" },

            // --- 负面情绪/拒绝 ---
            { label: "哭哭", url: "https://files.catbox.moe/rw1cfk.png" },
            { label: "大哭", url: "https://files.catbox.moe/dbyrdf.png" },
            { label: "委屈", url: "https://sharkpan.xyz/f/gVySw/D90D0B53802301FCDB1F0718DEB08C79_0.gif" },
            { label: "生气", url: "https://files.catbox.moe/si6f0k.png" },
            { label: "不爽", url: "https://files.catbox.moe/amelbv.png" },
            { label: "嫌弃", url: "https://files.catbox.moe/t2e0nt.png" },
            { label: "无语", url: "https://files.catbox.moe/wgkwjh.png" },
            { label: "拒绝", url: "https://files.catbox.moe/bos6mn.jpg" },
            { label: "心碎", url: "https://files.catbox.moe/ueqlfe.jpg" },
            { label: "压力", url: "https://files.catbox.moe/ufz3ek.jpg" },

            // --- 攻击性/怼人 ---
            { label: "顶嘴", url: "https://sharkpan.xyz/f/vVBtL/mmexport1737057690899.png" },
            { label: "揍你", url: "https://sharkpan.xyz/f/oJ1i4/mmexport1737057862640.gif" },
            { label: "撞飞", url: "https://sharkpan.xyz/f/zMZu5/mmexport1737057848709.gif" },
            { label: "锁喉", url: "https://files.catbox.moe/mi8tk3.jpg" },
            { label: "滚", url: "https://sharkpan.xyz/f/1vAc2/mmexport1737057678306.png" },
            { label: "比中指", url: "https://files.catbox.moe/umpgjb.jpg" },
            { label: "吃屎", url: "https://files.catbox.moe/r26gox.png" },
            { label: "你是坏蛋", url: "https://sharkpan.xyz/f/8r2Sj/mmexport1737057726579.png" },
            { label: "我恨你", url: "https://files.catbox.moe/r6g32h.png" },
            { label: "别动量下腰围", url: "https://files.catbox.moe/别动量下腰围tmm57s.jpg" },
            { label: "竖中指", url: "https://files.catbox.moe/z25fao.png" },

            // --- 搞笑/发疯/阴阳怪气 ---
            { label: "疑惑", url: "https://files.catbox.moe/gofdox.jpg" },
            { label: "震惊", url: "https://files.catbox.moe/q7683x.png" },
            { label: "尴尬", url: "https://files.catbox.moe/8eaawd.png" },
            { label: "偷看", url: "https://files.catbox.moe/72wkme.png" },
            { label: "发疯", url: "https://files.catbox.moe/8cqr43.jpg" },
            { label: "已老实", url: "https://files.catbox.moe/6eyzlg.png" },
            { label: "喝茶", url: "https://files.catbox.moe/1xvrb8.jpg" },
            { label: "免礼", url: "https://sharkpan.xyz/f/pO6uQ/mmexport1737057701883.png" },
            { label: "满意", url: "https://sharkpan.xyz/f/e8KUw/mmexport1737057664689.png" },
            { label: "好困", url: "https://files.catbox.moe/7pncr1.jpg" },
            { label: "躺平", url: "https://files.catbox.moe/cq6ipd.png" },
            { label: "升天", url: "https://files.catbox.moe/o8td90.png" },
            { label: "大脑短路", url: "https://files.catbox.moe/d41e2q.png" },
            { label: "吃瓜", url: "https://files.catbox.moe/428w1c.png" },
            { label: "吐魂", url: "https://files.catbox.moe/7yejey.png" },
            { label: "问号", url: "https://files.catbox.moe/to45ts.png" },
            { label: "惊讶", url: "https://files.catbox.moe/惊讶wcxabf.png" },
            { label: "啧", url: "https://files.catbox.moe/啧w206rr.png" },
            { label: "多喝热水", url: "https://files.catbox.moe/多喝热水gs9ppe.png" },
            { label: "这是屎吗", url: "https://files.catbox.moe/这是屎吗r26gox.png" },

            // --- 特殊类 ---
            { label: "我是你的狗", url: "https://files.catbox.moe/1bki7o.jpg" },
            { label: "汪", url: "https://files.catbox.moe/iwmiww.jpg" },
            { label: "投降", url: "https://files.catbox.moe/f4ogyw.png" },
            { label: "爱你", url: "https://files.catbox.moe/x5u5sm.png" }
        ]
    };
})();
